version: '3'

networks:
  backend:
    driver: bridge

volumes:
  neo4j:
    driver: local

services:

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/logs:/logs
      - ./docker/neo4j/plugins:/plugins
      - ./docker/neo4j/conf:/conf
    networks:
      - backend

  worker:
    build: ./packages/postmodern-worker
    networks:
      - backend
    volumes:
      - ./corpus:/usr/src/app/corpus:ro
      - ./docker/worker/log:/root/.npm/_logs
    links:
      - neo4j
      - mongo
    depends_on:
      - neo4j
      - mongo

  mongo:
    image: mongo
    restart: always
    command:
      - "-f"
      - "/etc/mongod.conf"
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/log:/data/log
      - ./docker/mongo/conf/mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo
    networks:
      - backend
